<?php

return [

    [
        'label' => 'Tableau de bord',
        'route_dashboard' => true,
        'roles' => ['secretariat_medical', 'referent_service', 'admin_aphp', 'operateur_titulaire', 'relecteur_valideur', 'admin_titulaire'],
        'disponible' => true,
        'badge' => null,
    ],
    [
        'label' => 'Mes demandes',
        'route' => 'demandes.index',
        'roles' => ['secretariat_medical', 'referent_service'],
        'disponible' => true,
        'badge' => 'mes_demandes',
    ],
    [
        'label' => 'Déposer une demande',
        'route' => 'demandes.create',
        'roles' => ['secretariat_medical', 'referent_service'],
        'disponible' => true,
        'badge' => null,
    ],
    [
        'label' => 'File de traitement',
        'route' => 'file-traitement.index',
        'roles' => ['operateur_titulaire', 'relecteur_valideur', 'admin_titulaire'],
        'disponible' => true,
        'badge' => 'file_traitement',
    ],
    [
        'label' => 'Transcription',
        'route' => 'transcription.index',
        'roles' => ['operateur_titulaire'],
        'disponible' => true,
        'badge' => 'a_transcrire',
    ],
    [
        'label' => 'Relecture & contrôle qualité',
        'route' => 'relecture.index',
        'roles' => ['relecteur_valideur'],
        'disponible' => true,
        'badge' => 'a_relire',
    ],
    [
        'label' => 'Validation',
        'route' => 'validation.index',
        'roles' => ['relecteur_valideur'],
        'disponible' => true,
        'badge' => 'a_valider',
    ],
    [
        'label' => 'Documents restitués',
        'route' => 'restitution.index',
        'roles' => ['secretariat_medical', 'referent_service'],
        'disponible' => true,
        'badge' => null,
    ],
    [
        'label' => 'Dossiers à restituer',
        'route' => 'restitution.a-generer',
        'roles' => ['relecteur_valideur', 'admin_titulaire'],
        'disponible' => true,
        'badge' => 'a_restituer',
    ],
    [
        'label' => 'Suivi & reporting',
        'route' => null,
        'roles' => ['admin_aphp', 'referent_service', 'admin_titulaire'],
        'disponible' => false,
        'sprint' => 8,
        'badge' => null,
    ],
    [
        'label' => 'Administration',
        'route' => null,
        'roles' => ['admin_titulaire'],
        'disponible' => false,
        'sprint' => 9,
        'badge' => null,
    ],
    [
        'label' => 'Gouvernance IA',
        'route' => null,
        'roles' => ['admin_aphp', 'admin_titulaire'],
        'disponible' => false,
        'sprint' => 10,
        'badge' => null,
    ],
    [
        'label' => 'Support & incidents',
        'route' => null,
        'roles' => ['secretariat_medical', 'referent_service', 'admin_aphp', 'operateur_titulaire', 'relecteur_valideur', 'admin_titulaire'],
        'disponible' => false,
        'sprint' => 11,
        'badge' => null,
    ],
    [
        'label' => "Journal d'audit",
        'route' => 'audit.index',
        'roles' => ['admin_titulaire', 'admin_aphp'],
        'disponible' => true,
        'sprint' => null,
        'badge' => null,
    ],
];